[pytest]
#总配置文件
#打印日志 保存位置 每次打印前删除旧日志
addopts = -s --alluredir=./allure-results --clean-alluredir
#测试用例的查找路径
testpaths = ./test_cases
#测试用例的文件名匹配模式
python_files = test_*.py
#测试类名匹配模式
python_classes = Test*
#测试方法名匹配模式
python_functions = test_*