[pytest]
# 1. 全局默认附加参数：允许打印输出，指定Allure数据生成目录，并每次清空旧数据
addopts = -s --alluredir=./allure-results --clean-alluredir

# 2. 指定总司令默认去哪个阵地找测试用例
testpaths = ./test_cases

# 3. 指定测试文件的命名规则（只打 test_ 开头的文件）
python_files = test_*.py

# 4. 指定测试类的命名规则（只打 Test 开头的类）
python_classes = Test*

# 5. 指定测试函数的命名规则（只打 test_ 开头的函数）
python_functions = test_*